#!/usr/bin/env node

/**
 * This script automatically generates explicit exports for the Prisma client
 * to avoid Next.js warnings about using `export *` with CommonJS modules.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PRISMA_INDEX_DTS = join(__dirname, '../generated/prisma/index.d.ts');
const OUTPUT_FILE = join(__dirname, '../src/index.ts');

function extractExports() {
  const content = readFileSync(PRISMA_INDEX_DTS, 'utf-8');

  // Extract const exports (enums and constants - these are runtime values)
  const constExports = new Set();
  const constRegex = /^export const (\w+):/gm;
  let match;
  while ((match = constRegex.exec(content)) !== null) {
    constExports.add(match[1]);
  }

  // Extract top-level type exports (excluding those that also have const exports)
  const typeExports = new Set();
  const typeRegex = /^export type (\w+)/gm;
  while ((match = typeRegex.exec(content)) !== null) {
    // Only add if it's not already a const export (enums have both)
    if (!constExports.has(match[1])) {
      typeExports.add(match[1]);
    }
  }

  // Extract namespace exports
  const namespaceExports = new Set();
  const namespaceRegex = /^export namespace (\$\w+|\w+)/gm;
  while ((match = namespaceRegex.exec(content)) !== null) {
    namespaceExports.add(match[1]);
  }

  // Always include these core exports
  const coreExports = ['PrismaClient', 'Prisma'];

  return {
    types: Array.from(typeExports).sort(),
    enums: Array.from(constExports).sort(),
    namespaces: Array.from(namespaceExports).sort(),
    core: coreExports
  };
}

function generateIndexFile(exports) {
  const { types, enums, namespaces, core } = exports;

  // Combine all value exports (core + enums + namespaces) and remove duplicates
  const allValueExports = [...new Set([...core, ...enums, ...namespaces])];

  const content = `// This file is auto-generated by scripts/generate-exports.js
// Do not edit manually - run 'pnpm db:generate' to regenerate

import { PrismaClient } from "../generated/prisma/index.js";

// Re-export Prisma client, enums, and namespaces explicitly to avoid Next.js CommonJS warnings
export {
  ${allValueExports.join(',\n  ')}
} from "../generated/prisma/index.js";

// Re-export all types (excluding enums which are exported above as values)
export type {
  ${types.join(',\n  ')}
} from "../generated/prisma/index.js";

// Prevent multiple instances of Prisma Client in development
declare global {
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined;
}

export const prisma =
  global.prisma ||
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  global.prisma = prisma;
}
`;

  return content;
}

try {
  console.log('🔍 Extracting exports from Prisma client...');
  const exports = extractExports();

  console.log(`✅ Found ${exports.types.length} types, ${exports.enums.length} enums, ${exports.namespaces.length} namespaces, ${exports.core.length} core exports`);

  console.log('📝 Generating index.ts...');
  const content = generateIndexFile(exports);

  writeFileSync(OUTPUT_FILE, content, 'utf-8');
  console.log('✅ Generated packages/database/src/index.ts');
} catch (error) {
  console.error('❌ Error generating exports:', error);
  process.exit(1);
}
