// This file is auto-generated by scripts/generate-exports.js
// Do not edit manually - run 'pnpm db:generate' to regenerate

import { PrismaClient } from "../generated/prisma/index.js";

// Re-export Prisma client, enums, and namespaces explicitly to avoid Next.js CommonJS warnings
export {
  PrismaClient,
  Prisma,
  AutoFixStatus,
  BackendMigrationStatus,
  CloudCreditPurchaseStatus,
  CloudCreditType,
  CodeImportSource,
  CodeImportStatus,
  ConnectorStatus,
  ConvexBillingStatus,
  ConvexDeploymentStatus,
  CreditGrantStatus,
  CreditType,
  DomainSSLStatus,
  DomainStatus,
  ErrorSeverity,
  ErrorStatus,
  ErrorType,
  ImportedFromPlatform,
  MembershipTier,
  MessageRole,
  MessageType,
  PaymentStatus,
  PersonalConnectorProvider,
  ProjectBuildStatus,
  PurchaseStatus,
  SharedConnectorType,
  SubscriptionStatus,
  TeamRole,
  UploadType,
  UserRole,
  $Enums
} from "../generated/prisma/index.js";

// Re-export all types (excluding enums which are exported above as values)
export type {
  Account,
  AutoFixSession,
  AutoTopUpConfig,
  ChatStream,
  CloudCreditPurchase,
  CloudCreditTransaction,
  CodeImport,
  CommunityTemplate,
  ComponentEditMetadata,
  ConvexDeployment,
  ConvexUsagePeriod,
  CreditPurchase,
  CreditTransaction,
  CustomDomain,
  Deployment,
  Fragment,
  GitFragment,
  HalChatMessage,
  HalInteraction,
  HalSuggestion,
  HalUserPreferences,
  Message,
  PersonalConnector,
  PrismaPromise,
  Project,
  ProjectError,
  Session,
  SharedConnector,
  StripeCreditGrant,
  Subscription,
  Team,
  TeamMember,
  TemplateCategory,
  TemplateChatMessage,
  TemplateComment,
  TemplateLike,
  TemplatePurchase,
  TemplateRemix,
  TemplateSave,
  Upload,
  User,
  V2Fragment,
  V2Message,
  VerificationToken,
  project_secrets
} from "../generated/prisma/index.js";

// Prevent multiple instances of Prisma Client in development
declare global {
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined;
}

export const prisma =
  global.prisma ||
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  global.prisma = prisma;
}
